name: CI Build & Push Docker Images

on:
  push:
    branches: ["main"]          # Tự động chạy khi push lên main
  workflow_dispatch:            # Có thể bấm chạy thủ công

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # --- BACKEND ---
      - name: Build Backend Image
        run: |
          cd backend
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ecom-backend:latest .

      - name: Push Backend Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/ecom-backend:latest

      # --- FRONTEND ---
      - name: Build Frontend Image
        run: |
          cd frontend
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ecom-frontend:latest .

      - name: Push Frontend Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/ecom-frontend:latest

      # --- NGINX ---
      - name: Build Nginx Image
        run: |
          cd nginx
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ecom-nginx:latest .

      - name: Push Nginx Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/ecom-nginx:latest