name: CI/CD Build & Push Docker

on:
  push:
    branches: ["main"]        # Chạy khi push code lên main
  workflow_dispatch:          # Cho phép bấm chạy thủ công

jobs:
  build_backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Login Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Backend Docker Image
        run: cd backend && docker build -t ${{ secrets.DOCKER_USERNAME }}/ecom-backend:latest .

      - name: Push Backend image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/ecom-backend:latest

  build_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Login Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Frontend Docker Image
        run: cd frontend && docker build -t ${{ secrets.DOCKER_USERNAME }}/ecom-frontend:latest .

      - name: Push Frontend image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/ecom-frontend:latest
